package core.Enums;

// TODO: add all factions
public enum Faction  {
    Aeldari,
    Craftworlds,
    Drukhari,
    Ynnari,
    ChaosDaemons,
    ChaosKnights,
    ChaosSpaceMarines,
    DeathGuard,
    EmperorsChildren,
    ThousandSons,
    TitanicusTraitoris,
    WorldEaters,
    GenestealerCults,
    AdeptaSororitas,
    AdeptusCustodes,
    AdeptusMechanicus,
    AdeptusTitanicus,
    AgentsofTheImperium,
    AstraMilitarum,
    BlackTemplars,
    BloodAngels,
    DarkAngels,
    Deathwatch,
    GreyKnights,
    ImperialFists,
    ImperialKnights,
    IronHands,
    RavenGuard,
    Salamanders,
    SpaceMarines,
    SpaceWolves,
    Ultramarines,
    WhiteScars,
    LeaguesofVotann,
    // Legens should not be supported really
    AstartesHeresyLegends,
    Titans,
    Tyranids,
    Necrons,
    Orks,
    TauEmpire,
    UnalignedForces,
    Unidentified;

}
